# Comments base
FROM yti-comments-ui-base

# Add nginx config
ADD nginx-docker-local.conf /etc/nginx/nginx.conf

# Build the dist dir containing the static files
WORKDIR /app
RUN ["npm", "run", "build", "--", "--output-hashing=all"]

# Start web server and expose http
EXPOSE 80
CMD ["nginx"]

